security:
    encoders:
        CCleanBundle\Entity\Client: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity:
                class:   CCleanBundle\Entity\Client
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /
            remember_me:
                key: %secret%
#            oauth:
#                resource_owners:
#                    facebook:           "/login-oauth/check-facebook"
#                    google:             "/login-oauth/check-google"
#                    twitter:            "/login-oauth/check-twitter"
#                login_path:        /login-oauth
#                use_forward:       false
#                failure_path:      /login-oauth
#
#                oauth_user_provider:
#                    service: cclean_user.oauth_user_provider

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/testimonial/new, roles: ROLE_USER}