security:
    encoders:
        CCleanBundle\Entity\Client: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity:
                class:   CCleanBundle\Entity\Client
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /
            remember_me:
                key: %secret%
            oauth:
                resource_owners:
                    facebook:           "/login-oauth/check-facebook"
                    google:             "/login-oauth/check-google"
                    twitter:            "/login-oauth/check-twitter"
                login_path:        /login-oauth
                use_forward:       false
                failure_path:      /login-oauth

                oauth_user_provider:
                    service: cclean_user.oauth_user_provider
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

#security:
#    encoders:
#        CCleanBundle\Entity\Client:
#            algorithm: bcrypt
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    providers:
#        our_db_provider:
#            entity:
#                class: CCleanBundle:Client
#                 # if you're using multiple entity managers
#                 # manager_name: customer
#
#    firewalls:
#        dev:
#            pattern:  ^/api/(_(profiler|wdt|doc))/
#            security: false
#        login_firewall:
#            pattern:    ^/login$
#            anonymous:  true
#        main:
#            pattern: ^/testimonial/new
#            form_login:
#                provider: our_db_provider
#                remember_me: true
#                target_path_parameter: redirect_url
#                login_path: login
#                check_path: login_check
#            logout:
#                path:   logout
#                target: /
#            remember_me:
#                secret:   '%secret%'
#                lifetime: 604800 # 1 week in seconds
#                path:     /
#                # by default, the feature is enabled by checking a
#                # checkbox in the login form (see below), uncomment the
#                # following line to always enable it.
#                #always_remember_me: true
#            anonymous:       true
#            logout:          true
#
#    access_control:
#        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/testimonial/new, roles: ROLE_USER}