# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    time_authenticator:
        class:     CCleanBundle\Security\TimeAuthenticator
        arguments: ["@security.password_encoder"]
