# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    orm_user.user_manager: Doctrine\Common\Persistence\ManagerRegistry

services:
    time_authenticator:
        class:     CCleanBundle\Security\TimeAuthenticator
        arguments: ["@security.password_encoder"]

    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    cclean_user.oauth_user_provider:
        class: CCleanBundle\Security\OAuthProvider
        arguments: [@session, @doctrine, @service_container]