<?php

namespace CCleanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AverageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AverageRepository extends EntityRepository
{
}
