<?php

namespace CCleanBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository implements UserLoaderInterface
{

    /**
     * @param string $username
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.mail = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param $username
     * @param $password
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function checkLogin($username, $password)
    {
        return $this->createQueryBuilder('c')
            ->where('c.username = :username AND c.password = :password')
            ->setParameter('username', $username)
            ->setParameter('email', $password)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
