<?php

namespace CCleanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TestimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findTestimonialByActive()
    {
        return $this->createQueryBuilder('t')
            ->leftJoin('CCleanBundle:Client', 'c')
            ->select('t.comment', 't.note', 'c.name', 'c.surname', 'c.username', 'c.company')
            ->where('t.isActive = :true')
            ->setParameter('true', 1)
//            ->groupBy('t.clientId')
            ->getQuery()
            ->getResult();
    }

    public function findTotalNoteByActive()
    {
        return $this->createQueryBuilder('t')
            ->select('t.note')
            ->where('t.isActive = :true')
            ->setParameter('true', 1)
            ->getQuery()
            ->getResult();
    }
}
