<?php

namespace CCleanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TestimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findTestimonialByActive()
    {
        return $this->createQueryBuilder('t')
            ->join('CCleanBundle:Client', 'c')
            ->select('t')
            ->addSelect('c')
            ->select('t.comment', 't.note', 't.createdAt', 't.updatedAt', 't.isActive', 'c.id', 'c.name', 'c.surname', 'c.username', 'c.company')
            ->where('t.isActive = :true')
            ->andWhere('t.clientId = c.id')
            ->setParameter('true', 1)
            ->groupBy('t.createdAt')
            ->orderBy('t.validatedAt', 'DESC')
            ->getQuery()
            ->getArrayResult();
    }

    public function findTotalNoteByActive()
    {
        return $this->createQueryBuilder('t')
            ->select('t.note')
            ->where('t.isActive = :true')
            ->setParameter('true', 1)
            ->getQuery()
            ->getResult();
    }
}
